### ISSUE TITLE
Build with devenv (Visual Studio) using * character in Project field

### ISSUE THREAD

**Issue by onooka** [mmajcica/DevEnvBuild#1]
The red arrows are wrong when I execute the build
But the green arrows are correct and works fine !!!
The solution has SQL (Business Intelligence)

![example_1](https://user-images.githubusercontent.com/41794338/43326454-786c6802-91a8-11e8-8f9c-abd1d0a52a75.jpg)

![example_2](https://user-images.githubusercontent.com/41794338/43326493-8b4bd962-91a8-11e8-852e-99e1e2b2c73e.jpg)

![example_3](https://user-images.githubusercontent.com/41794338/43326527-a11dfc16-91a8-11e8-8198-48a86269aff4.jpg)

![example_4](https://user-images.githubusercontent.com/41794338/43326539-a4faf7d0-91a8-11e8-9991-f0035ae38ade.jpg)

Best Regards

Ernesto Ono

**Comment by mmajcica** [comment]
Hi Ernesto,

I'm working on it and I can hopefully test a new version this weekend. I'll let you know more as soon as I publish it.

**Comment by Dedac** [comment]
Any news on this?

**Comment by mmajcica** [comment]
Better late than never, today a new version will be released. In between other improvements, it will also solve this issue.
