### ISSUE TITLE
Azure Pipeline SSIS Build Failing

### ISSUE THREAD

**Issue by jdoucette108** [mmajcica/DevEnvBuild#10]
I have an SSIS project that uses the Azure Storage Connection Manager from SSIS Azure Feature Pack. When this connection is included in the project, the Azure Pipeline Build fails with the following message:

System.ArgumentException: Value does not fall within the expected range. at Microsoft.SqlServer.Dts.Runtime.Interop.ProjectInterop.ReferencePackage(Package package, String packageLocation) at Microsoft.SqlServer.Dts.Runtime.PackageItem.Load(IDTSEvents events) at Microsoft.SqlServer.Dts.Runtime.PackageItem.get_Package() at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.IncrementalBuildThroughObj(IOutputWindow outputWindow) at Microsoft.DataTransformationServices.Project.DataTransformationsProjectBuilder.BuildIncremental(IOutputWindow outputWindow)

When the Azure Storage Connection Manager is removed the the project, the Azure Pipeline Build is successful.

Microsoft Visual Studio Community 2019 Version 16.3.9 VisualStudio.16.Release/16.3.9+29509.3
SQL Server Data Tools 16.0.61908.27190
SQL Server Integration Services 15.0.1900.73

**Comment by mmajcica** [comment]
is this relevant to DevEnvBuild task or my SSIS task?

**Comment by jdoucette108** [comment]
Hi, it is for the DevEnvBuild task but I believe i was getting the same error on the SSIS task. I can confirm for you. I had an issue open with Microsoft and they closed it and suggested opening an issue here.

**Comment by mmajcica** [comment]
can you run the failing build with system.debug = true variable and share the log files?

**Comment by jdoucette108** [comment]
Please see attached. I removed our server names and package names but everything else is from the debug run.

[3_Build SSIS Project copy.txt](https://github.com/mmajcica/DevEnvBuild/files/3870174/3_Build.SSIS.Project.copy.txt)

Thank you for taking a look!

**Comment by mmajcica** [comment]
It looks to me that the task does what it needs to, collects all of the necessary information and invokes VS. Following is the executed command:
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.com" "D:\a\8\s\ARF-BIDW\ARF-BIDW.sln" /Project "D:\a\8\s\ARF-BIDW\ARF-BIDW-SSIS\ARF-BIDW-SSIS.dtproj" /Build Development`
Now it is Visual Studio failing, no matter if you do execute this through the task or from the command line, the result will be identical.
This is not to be attributed to the task itself but to Visual Studio.

**Comment by jdoucette108** [comment]
Thanks Mario, perhaps it is an issue with the Azure resource then. On my local machine I have the Azure feature pack installed, but if a resource is spun up to do the Azure pipeline, it may not include the feature pack. I will open another ticket with Microsoft.

**Comment by mmajcica** [comment]
Let us know how it ended, it may help others.
