### ISSUE TITLE
Build is Succesful but build artifact are not genarating

### ISSUE THREAD

**Issue by MurtajaKadiyani** [mmajcica/DevEnvBuild#12]
Hi,

I am trying to build .sln file which have SSIS project using build task. I have provided path of .sln file which is on TFS to Solution / Project field and kept rest of the fields blank. Now build pipeline is running fine but no artifact is generating and I am seeing warning message "Directory 'D:\buildagent_1\_work\58\a' is empty. Nothing will be added to build artifact 'drop'."

Can you please guide me on the same.

**Comment by mmajcica** [comment]
You can always check my blog post, http://blog.majcica.com/2018/04/25/deploy-ssis-packages-from-tfs-vsts-build-release/ If this does not help, or artifact is not generated or it is placed in a non standard location. Take a look in the logs what is going on with the artifact, I suppose there should be a trace about it.
