### ISSUE TITLE
Vdproj failures

### ISSUE THREAD

**Issue by bhardwajKY** [mmajcica/DevEnvBuild#18]
we usually get an error saying unable to open project when we build .vdproj locally, we just ignore it and still get the .msi output. But as this extension does not have a 'continueonerror:true' option, any suggestion on how to get success on building this task?
 
Error in UpgradeLog file:
path to vdproj\filename.vdproj:
Unable to open project '$(Build.SourceDirectory\filename.vdproj'.

**Comment by mmajcica** [comment]
In case you would like to add that as an option on the task, I'll be happy to merge a PR and publish it.
