### ISSUE TITLE
Solution SSIS with Password (EncryptSensitiveWithPassword)

### ISSUE THREAD

**Issue by onooka** [mmajcica/DevEnvBuild#2]
Hi

I have an solution SSIS with password; and I am using in the Configuration field:

Method 1
/p:ProtectionLevel="EncryptAllWithPassword",ProjectPassword="xxx"

Method 2
/p:SSISProj=”ERMX.FuelRoute.SSIS”,Configuration=”Development”,ProtectionLevel=”EncryptAllWithPassword”,ProjectPassword=”xxx″,ProjectName=”ERMX.FuelRoute.SSIS”

But The build does not working

If the solution has not password, the DevEnv Works very well !!!!

How can I setting the configuration if the solution has password "EncryptAllWithPassword"

Best regards

**Comment by mmajcica** [comment]
Hi,

can you give me an example on how would you invoke this from the command line? What is a precise command/parameter and where are those documented?

**Comment by onooka** [comment]
Hi

I found this program build and works very well !!!! When the solution SSIS has password encrypted

https://github.com/rtumaykin/ssis-build

Best regards

**Comment by mmajcica** [comment]
Well, this is a task that triggers the build with devenv.com. What you are suggesting is to use a custom tool. That is out of the scope.
