### ISSUE TITLE
hi we are using to build our solution devenv build tool .but we are geting Process 'devenv.com' exited with code '1 .and its telling that ."The license for Visual Studio has expired."

### ISSUE THREAD

**Issue by Pashanaz** [mmajcica/DevEnvBuild#24]

**Comment by Pashanaz** [comment]
hi we are using to build our solution devenv build tool .but we are geting Process 'devenv.com' exited with code '1 .and its telling that ."The license for Visual Studio has expired.Please help me on this already we update the licnese version of my visual studio still gettign same issue.

**Comment by Pashanaz** [comment]
Its a prod issue plase help me :9705276965

**Comment by Pashanaz** [comment]
![image](https://user-images.githubusercontent.com/101168040/157184193-a0691f76-5ce0-46ba-b9f9-deab86c2782e.png)

**Comment by Pashanaz** [comment]
![image](https://user-images.githubusercontent.com/101168040/157184350-b80c9947-cbb8-43f9-989d-88850be73462.png)

**Comment by cbolsen** [comment]
You might need to change the user account used by the VS agent to the one that installed and authenticated VS. You can configure this with config.cmd.

**Comment by Galatis-Giuliano** [comment]
> You might need to change the user account used by the VS agent to the one that installed and authenticated VS. You can configure this with config.cmd.

I see that this issue is closed but I am having the same issue and can't seem to find a solution. Do you know what the steps to do this would be?
