### ISSUE TITLE
Build pipeline failed with Devenv.com with exit code 1. We are using VS2022 version.

### ISSUE THREAD

**Issue by Dhanudj** [mmajcica/DevEnvBuild#28]
We are using VS2022 it worked fine with version 17.5.3 recently version was updated to 17.5.5 and above it started throwing an error and our support team mentioned that it will no longer work when future updates happened in the agent pool.

2023-06-05T10:06:32.8620651Z ##[error]Process 'devenv.com' exited with code '1'.

**Comment by dumbu437** [comment]
We are facing similar issue when Vs version upgrade happens this issue is repeating. Will there be any work around to fix this ? Could you please help us on this @mmajcica

**Comment by mmajcica** [comment]
Hi, I'm not supporting this code for quite some time now. At the moment I have no time and interest to dedicate to this task/extension. However, in case you know how to fix this, I'll be happy to pick up a PR and publish a new version of it.
