### ISSUE TITLE
Field for additional build parameters

### ISSUE THREAD

**Issue by salixzs** [mmajcica/DevEnvBuild#3]
Excellent extension. One thing I miss is to be able to pass additional parameters for build.
It would be good (and IMHO easy) to add a field similar to MSBuild and VSBuild tasks - additional MSBuild parameters.

**Comment by mmajcica** [comment]
Do you have an example on how you will pass those on the cmdline?

**Comment by pvredeveld** [comment]
for example to add the /parameterconfig parameter. This required parameters (when the project argument is set) is missing in de available settings.
