### ISSUE TITLE
Error creating window handle

### ISSUE THREAD

**Issue by mheptinstall** [mmajcica/DevEnvBuild#4]
When trying to build a solution/project of SQL Server Integration Services projects in a pipeline using this task I receive the error "Error creating window handle" for certain projects in my solution.

```
##[section]Starting: Build project: $/Data Warehouse/Main/Packages/Packages.sln
==============================================================================
Task         : DevEnv build (Visual Studio)
Description  : Build a project via the visual studio command-line invocation, devenv.cmd
Version      : 1.2.0
Author       : Mario Majcica
Help         : Build your project via the visual studio command-line invocation, devenv.cmd
==============================================================================
##[command]"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.com" "C:\agent\_work\27\s\Packages.sln" /Build Dev

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.
C:\agent\_work\27\s\SexualHealth.Pathology\Packages.SexualHealth.Pathology.dtproj : error  : Error creating window handle.


One or more projects in the solution were not loaded correctly.
##[error]Process 'devenv.com' exited with code '255'.
##[section]Finishing: Build project: $/Data Warehouse/Main/Packages/Packages.sln
```

Running the equivalent via the Command Line task in Azure DevOps produces the same error, if I use the /Project switch to specify a project different to the one that errors I still get the same error.

This only occurs when trying to build from Azure DevOps using the private agent. Executing the same command when logged onto the server where the agent is hosted produces no error when I build the solution or a specific project.

Visual Studio 2015 Community Update 3 is installed on the server along with SQL Server Data Tools 2015 17.4

I'm struggling to identify what the issue could be, any suggestions on how to diagnose further?

**Comment by mmajcica** [comment]
Hi Mark,

I have never seen an error of this kind. May it has to do with a library or something that requires the interactive execution. Execution of tasks on the agent is done with the following parameters "-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted".  Can you try to mimic that on the server that you were testing with success?
