### ISSUE TITLE
Unable to add task once installed

### ISSUE THREAD

**Issue by cstwig** [mmajcica/DevEnvBuild#5]
Once I have installed the extension, I'm not able to pick it as a build event - there is no "Add" button - am I missing something?

![image](https://user-images.githubusercontent.com/40690926/49438422-35970b80-f7b6-11e8-9c0e-7b823903d290.png)

**Comment by mmajcica** [comment]
Hi,

I just installed it cleanly in a new organization on VSTS and this is what I do see.
![image](https://user-images.githubusercontent.com/3026551/49440351-b14b8500-f7c3-11e8-8a0e-e587b8557dce.png)


Maybe a stupid question, but have you refreshed the page after you installed the extension?

**Comment by mmajcica** [comment]
Also, the question is, is this TFS or VSTS?
Second, have you tried ever uploading the task manually with TFX-CLI?

**Comment by cstwig** [comment]
Hi, thanks for the quick response. It was a problem our end - I think it was permission based as I got our system admin to install the extension and it deployed properly.
