### ISSUE TITLE
Argument transformation error

### ISSUE THREAD

**Issue by janissimsons** [mmajcica/DevEnvBuild#6]
Hi,
We have been using this Azure task for several months and it was working fine, but then suddenly it started failing on all our builds with the same error:

`##[error]Cannot process argument transformation on parameter 'FileName'. Cannot convert value to type System.String.`

Do you know what could be causing this issue? We have not changed the build definition, we are still sending the same parameters as before.

![image](https://user-images.githubusercontent.com/6424248/59408315-72266e00-8dbc-11e9-92f2-e2a4f5e848ed.png)

**Comment by mmajcica** [comment]
HI,

I see you are still using version 1.2.0. Can you please try with the 2.0.5 and check if the same is happening?

**Comment by MikeCheel** [comment]
I'm getting this exact error today and I am using version 2 of the task. Any solution to this error?
